services:
  # ===========================
  # PostgreSQL Database
  # ===========================
  postgres:
    image: postgres:15
    container_name: dc_sms_portal_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dcadmin -d dc_sms_portal_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ===========================
  # pgAdmin (Database GUI)
  # ===========================
  pgadmin:
    image: dpage/pgadmin4
    container_name: dc_sms_portal_pgadmin_client
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kwadjodanq@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dcadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # ===========================
  # Redis (Optional)
  # ===========================
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # ===========================
  # Backend API (Node.js)
  # ===========================
  backend:
    image: danald/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: dc_sms_portal_backend_api
    command: npm run devStart
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
    environment:
      DOCKER: "true"
      NODE_ENV: development
      DB_HOST: postgres
      DB_USER: dcadmin
      DB_PASSWORD: dcadmin
      DB_NAME: dc_sms_portal_db
      DB_PORT: 5432
      SMS_PROVIDER_API_URL: https://sms.arkesel.com/api/v2/sms/send
      SMS_PROVIDER_API_KEY: OkFLYmVtaUI4MmVJM09kejI=
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    
  sms-worker:
    image: danald/backend:latest
    working_dir: /app
    environment:
      DB_HOST: postgres
      DB_USER: dcadmin
      DB_PASSWORD: dcadmin
      DB_NAME: dc_sms_portal_db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  
  # ===========================
  # Frontend (React â†’ Nginx)
  # ===========================
  frontend:
    image: danald/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dc_sms_portal_frontend_app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: